name: chatview_utils
description: Utility library for the chatview and chatview_connect libraries, containing shared type declarations. It should not be used directly.
version: 0.0.2
repository: https://github.com/merterkoc/chatview_utils
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview_utils/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
